name: CI/CD Stable Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
  - branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest || echo "No tests"

    - name: OWASP Dependency Check
      run: bash security/dependency_check.sh
    
   -  name: Login to Docker Hub
      use: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  
    - name: Build Docker image
      run: docker build -t sanskrutisardare1/devsecops-stable:latest ./app

    - name: Trivy Scan
      run: bash security/trivy_scan.sh sanskrutisardare1/devsecops-stable:latest

    - name: Build and Push Docker image
      run: |
        docker build -t sanskrutisardare1/devsecops-stable:latest ./app
        docker push sanskrutisardare1/devsecops-stable:latest
