name: CI/CD Stable Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest || echo "No tests"

    - name: OWASP Dependency Check
      run: bash security/dependency_check.sh

    - name: Build Docker image
      run: docker build -t sanskrutisardare1/devsecops-stable:latest ./app

    - name: Trivy Scan
      run: bash security/trivy_scan.sh sanskrutisardare1/devsecops-stable:latest

    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u sanskrutisardare1 --password-stdin
        docker push sanskrutisardare1/devsecops-stable:latest
