name: CI/CD Stable Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    
    # 1️⃣ Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3️⃣ Install dependencies & run tests
    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt
        pip install pytest
    - name: Run tests
      run: pytest || echo "No tests"

    # 4️⃣ OWASP Dependency Check
    - name: OWASP Dependency Check
      run: bash security/dependency_check.sh

    # 5️⃣ Docker Hub Login
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 6️⃣ Build Docker image
    - name: Build Docker image
      run: docker build -t sanskrutisardare1/devsecops-stable:latest ./app

    # 7️⃣ Trivy Security Scan
    - name: Trivy Scan
      run: bash security/trivy_scan.sh sanskrutisardare1/devsecops-stable:latest

    # 8️⃣ Push Docker image to Docker Hub
    - name: Push Docker image
      run: docker push sanskrutisardare1/devsecops-stable:latest

